a = input('Digite alguma coisa: ')
print('O tipo prim desse valor e ', type(a))
print('So espaços?', a.isspace())
print('E numero?', a.isnumeric())
print ('E alfabetico', a.isalpha())
print ('E alfanumerico', a.isalnum())
print ('Esta em maiusculas', a.isupper())
print ('Esta em minusculas', a.islower())
print ('Esta capitalizada', a.istitle())
